# Generated by Django 3.0.5 on 2021-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0002_transec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transec',
            name='receiver',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transec',
            name='senderName',
            field=models.CharField(max_length=30),
        ),
    ]
