# Generated by Django 3.0.5 on 2021-01-11 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transection', '0003_auto_20210111_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transec',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
